### ISSUE TITLE
Browser query (MATCH_ALL)

### ISSUE THREAD

**Issue by idomo1** [okta/okta-mobile-kotlin#179]
### Describe the feature request?

The old SDK allowed setting the MATCH_ALL flag for the browser query. Enabling this resolved most of the reports we were getting for the SDK failing to find a browser.

I don’t see this option with this new SDK (please correct me if I’m wrong). Are the issues with finding browsers going to come back?

### New or Affected Resource(s)

No idea

**Comment by JayNewstrom** [comment]
I think we've fixed most issues with browser compatibility by default in the new SDK! So I don't expect you'll need to customize that flag.  Please give it a try and let me know. 

The new SDK is actually far more configurable, so I can point you in the direction of how to customize it if you find you need to.

**Comment by idomo1** [comment]
That's great to hear! We won't know for sure until it's tested in production. If we start getting lots of those reports again I'll raise a new issue.
