### ISSUE TITLE
Support for Unlock a mobile app with biometrics

### ISSUE THREAD

**Issue by ritesh-spoton** [okta/okta-mobile-kotlin#193]
### Describe the feature request?

Please add support to integrate biometric authentication like Face ID and Touch ID to your mobile apps that use Okta, this feature was supported in legacy sdk: https://developer.okta.com/docs/guides/unlock-mobile-app-with-biometrics/android/main/ 

### New or Affected Resource(s)

Authentication

### Provide a documentation link

https://developer.okta.com/docs/guides/unlock-mobile-app-with-biometrics/android/main/

**Comment by JayNewstrom** [comment]
You should be able to use the [TokenStorage](https://okta.github.io/okta-mobile-kotlin/auth-foundation/com.okta.authfoundation.credential/-token-storage/index.html) interface to implement this. That being said, we haven’t yet put a sample together, or updated the guide for this. We do plan to update the sample and guide, and it’s on our backlog.

**Comment by JayNewstrom** [comment]
@ritesh-spoton I've added support to the SDK here: https://github.com/okta/okta-mobile-kotlin/pull/207 (not yet released). We plan to make updates to the docs/samples soon, but it should be pretty easy to integrate!

**Comment by ritesh-spoton** [comment]
Hi @JayNewstrom when is the next release scheduled with the above changes?

**Comment by JayNewstrom** [comment]
Hi @ritesh-spoton we're hoping to land another change before doing a 1.1. We don't typically give estimates on release dates. But I'd hope to see a 1.1 soon.

**Comment by JayNewstrom** [comment]
Released as 1.1.0 https://github.com/okta/okta-mobile-kotlin/blob/master/CHANGELOG.md#110---2022-09-13
