### ISSUE TITLE
Add client assertion as optimal parameter on Authorization Code Flow 

### ISSUE THREAD

**Issue by knsjk1204** [okta/okta-mobile-kotlin#206]
### Describe the feature request?

I'm not sure if client assertion should be supported by okta-mobile SDK,client assertion used to be prevent replay attacks. but when I was looking at the documents for request  token, I noticed that there are two parameters: client_assertion_type and client_assertion. Do these two parameters need to be added to native SDK? Alternatively, is rfc7521 still the best current practice?

https://www.rfc-editor.org/rfc/rfc7521.html#section-4.2

 POST /token HTTP/1.1
 Host: server.example.com
 Content-Type: application/x-www-form-urlencoded

 grant_type=authorization_code&
 code=n0esc3NRze7LTCu7iYzS6a5acc3f0ogp4&
 client_assertion_type=urn%3Aietf%3Aparams%3Aoauth
 %3Aclient-assertion-type%3Asaml2-bearer&
 client_assertion=PHNhbW...[omitted for brevity]...Z

### New or Affected Resource(s)

https://www.rfc-editor.org/rfc/rfc7521.html#section-4.2
https://www.rfc-editor.org/rfc/rfc8252#section-8.5

**Comment by knsjk1204** [comment]
Hi @JayNewstrom ,thanks for reply, it's for purely enhanced security, I checked https://datatracker.ietf.org/doc/draft-ietf-oauth-security-topics/, and they explained that Authorization servers SHOULD use client authentication if possible. Because server-side recommends using client assertion, but what native SDK? I'm not fully understand how client assertion works. Documents also explain that PKCE is not a replacement for client authentication and that it does not allow treating a public client as a confidential client. https://oauth.net/2/pkce/  . Client assertion is mentioned in a lot of documents, but seems it never be used in native application sdk. I am just wondering why?

**Comment by JayNewstrom** [comment]
Hi @knsjk1204 after talking with the security team. They are in agreement that the Android SDK consumers (Android apps) should never be a confidential client. 

I'm going to close this for now, as we don't have plans to implement this. 

If you have a use case for this, please feel free to reach out to support or your customer success manger.

**Comment by knsjk1204** [comment]
@JayNewstrom ,thanks for explanation, because client assertion is only used in confidential client, but since native application ( android & ios app) should never be a confidential client for security reason ,so that's why okta team don't have plans to implement this. did I understand correctly?sorry for asking again, Is any documents related about client_assertion only should be using on confidential client?

**Comment by JayNewstrom** [comment]
client assertion _can_ be used in public clients as well. That being said, the biggest reason to choose client assertion is to use a confidential client without exposing the secret (using public key cryptography). 

We don't see a use case for Android apps with this feature.
