### ISSUE TITLE
Expose a Credential Token in a Coroutines StateFlow

### ISSUE THREAD

**Issue by frett** [okta/okta-mobile-kotlin#210]
### Describe the feature request?

Modern UI frameworks are built around observable data (`LiveData`, `StateFlow`, `State` in Jetpack Compose). Currently none of the objects within the SDK expose their data in an observable form. This means that external logic needs to be implemented to cause UIs to manually refresh their snapshot of data when state within the Okta SDK is updated.

This feature request is basically requesting that the `Credential` object exposes its current token via a `StateFlow` which would allow UIs to monitor the token for changes and automatically refresh their UI.

The reason I'm asking for access to the `token` in an observable format is to automatically drive a UI change when the user is logged in vs logged out.

While you are at it, it might be beneficial to also expose the `tags` via a `StateFlow` as well.

### New or Affected Resource(s)

This should only affect the `Credential` object.

### Additional Information?

I'd imagine this could be implemented via storing the private `_token` var as a `MutableStateFlow<Token?>`.
All access to it can then be accomplished internally using `_token.value`.
And a new property could be exposed: `val tokenStateFlow: StateFlow<Token?> get() = _token`

**Comment by frett** [comment]
The reason I'm suggesting using `StateFlow` over the other observable data types is because you have already embraced coroutines throughout this SDK, so utilizing the coroutines `StateFlow` object seems like a natural solution.

a StateFlow can easily be transformed into the other observable state objects without any code necessary in the Okta SDK.

**Comment by JayNewstrom** [comment]
Thanks for the feature request @frett 

Overall I think it's a good idea, and would likely be beneficial. 

We already expose some things that might enable you to build this outside the SDK (https://okta.github.io/okta-mobile-kotlin/auth-foundation/com.okta.authfoundation.client.events/-token-created-event/index.html)

That being said, I'm not opposed to exposing this from within the SDK. I do think there may be some edge cases (deleting a credential should close the flow, etc) that need to be thought through/tested. 

If you're up for creating a PR, we'd accept a contribution for this. If not that's okay too, I can leave this open as a potential future addition.

**Comment by frett** [comment]
Unfortunately the `TokenCreatedEvent` is fired off before the `token` is stored in the `Credential` object. This is susceptible to a race condition, which I'm currently experiencing locally.

I've also tried wrapping the `TokenStorage` object to observe whenever there are changes to storage to trigger the refresh, and this is hitting the same race condition due to the storage being updated before the in-memory Credential object.

Those workarounds will all be moot once we sort out the PR :)

**Comment by JayNewstrom** [comment]
Yeah, I think we should try to fix this from both sides. I'll separately look into moving the events until after those actions occur.
