### ISSUE TITLE
Support overloads generation for Java

### ISSUE THREAD

**Issue by hungweng** [okta/okta-mobile-kotlin#225]
### Describe the feature request?

Can we add the [@JvmOverloads](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-overloads/index.html) annotation to functions with default parameter values to make it easier to be used by Java? (Unless this SDK is not supposed to be used by an Android project written in Java)

### New or Affected Resource(s)

Functions with default parameters

**Comment by JayNewstrom** [comment]
Due to extensive use of kotlin coroutines, we don't support consuming the SDK via java.
