### ISSUE TITLE
Failure in calling setUserAuthenticationParameters(30, KeyProperties.AUTH_BIOMETRIC_STRONG)

### ISSUE THREAD

**Issue by ritesh-spoton** [okta/okta-mobile-kotlin#226]
### Describe the bug?

Getting below error:
`java.lang.NoSuchMethodError: No virtual method setUserAuthenticationParameters(II)Landroid/security/keystore/KeyGenParameterSpec$Builder; in class Landroid/security/keystore/KeyGenParameterSpec$Builder; or its super classes (declaration of 'android.security.keystore.KeyGenParameterSpec$Builder' appears in /system/framework/framework.jar!classes2.dex)`

Code:
`val specBuilder = KeyGenParameterSpec.Builder(
    "com_spoton_flex_auth_okta_storage",
     KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
 )`
`.setBlockModes(KeyProperties.BLOCK_MODE_GCM)`
`.setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)`
`.setUserAuthenticationRequired(true)`
`.setUserAuthenticationParameters(30, KeyProperties.AUTH_BIOMETRIC_STRONG)`
`.setKeySize(256)`
`val spec = specBuilder.build()`

### What is expected to happen?

It should be able to create okta client and login.

### What is the actual behavior?

App crashes.

### Reproduction Steps?

Login with the above code.

### Additional Information?

DeviceOs: Android 9

### SDK Version and Artifact(s) used.

`
implementation(platform('com.okta.kotlin:bom:1.1.0'))
implementation('com.okta.kotlin:auth-foundation')
implementation('com.okta.kotlin:auth-foundation-bootstrap')
implementation('com.okta.kotlin:oauth2')
implementation('com.okta.kotlin:web-authentication-ui')
`

**Comment by JayNewstrom** [comment]
The method you're calling was added in Android API level 30, Android 9 is API level 28.

https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationParameters(int,%20int)

You'll need to either not support older versions if you want to use that method, or conditionally call it by wrapping it in an if check.

Feel free to reopen with further questions.
