### ISSUE TITLE
defaultCredentialDataSource()

### ISSUE THREAD

**Issue by skdesarrollo** [okta/okta-mobile-kotlin#232]
### Describe the bug?

val credentialDataSource: CredentialDataSource = CredentialBootstrap.defaultCredentialDataSource()
This extension fuction doesn't exit and the exchange token is not clear about how to use this__

### What is expected to happen?

            val credentialDataSource: CredentialDataSource = CredentialBootstrap.defaultCredentialDataSource()
found the extension fuction

### What is the actual behavior?

Unresolved reference: defaultCredentialDataSource

### Reproduction Steps?

write this line
val credentialDataSource: CredentialDataSource = CredentialBootstrap.defaultCredentialDataSource()

### SDK Version and Artifact(s) used.

1.1.1

**Comment by rajdeepnanua-okta** [comment]
@skdesarrollo, thanks for bringing this to our attention! It should be CredentialBootstrap.credentialDataSource. I noticed that the README mentions this non-existing API. I will put up a fix for this. If you noticed this in any other documentation than the README, please let me know about that as well so I can get that fixed.
