### ISSUE TITLE
"Site can’t be reached" when using compose

### ISSUE THREAD

**Issue by kkiermasz** [okta/okta-mobile-kotlin#241]
### Describe the bug?

Hello!
When using the app with a jetpack compose UI, Okta callback cannot be handled. The same setup provided to the demo app works pretty well, so it is unrelated to Okta configuration. I suspect something is not set up correctly in my app, but I'd be grateful for any help and for adjusting the docs for composing in the future.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/20985075/224728954-7cea3484-1aa8-45be-a2a6-3205ad8a0d18.png">

### What is expected to happen?

Receive `OidcClientResult<Token>`

### What is the actual behavior?

Stuck in the redirection chain

### Reproduction Steps?

Tap Login button

### Additional Information?

Demo: https://github.com/kkiermasz-spoton/OktaIssueDemo

### SDK Version and Artifact(s) used.

1.1.2

**Comment by rajdeepnanua-okta** [comment]
Hi @kkiermasz, in https://github.com/kkiermasz-spoton/OktaIssueDemo/blob/main/app/build.gradle.kts, I noticed that you have manifestPlaceholders["webAuthenticationRedirectScheme"] set up incorrectly. That should be the same value as what you're setting as signInRedirectUri in okta.properties.

**Comment by kkiermasz** [comment]
Hi @rajdeepnanua-okta, thank you for your response!
I'm confused now. As I told above, using your demo app called `Browser sign in` with my setup works perfectly. 
I'm almost sure that you overlooked something. [Here](https://github.com/okta-samples/okta-android-kotlin-sample/blob/987d31c2714492b8104a0df50e738d4c3b671683/app/build.gradle#L26) you can see, that `signInRedirectUri` is accessed via [`parseScheme`](https://github.com/okta-samples/okta-android-kotlin-sample/blob/987d31c2714492b8104a0df50e738d4c3b671683/app/build.gradle#L50) method, which translates it precisely to what my setup provides to `manifestPlaceholders` explicitly.
However, if you'd like to check it, [here](https://github.com/kkiermasz-spoton/OktaIssueDemo/tree/signInRedirectUri) you can find the branch with the proposed fix.

**Comment by rajdeepnanua-okta** [comment]
Hi @kkiermasz, I looked into the issue in some more detail and noticed that there was a slight issue with quotes ending up in manifestPlaceholders. I made these changes and am seeing the redirect work:
```diff
--- a/app/build.gradle.kts
+++ b/app/build.gradle.kts
@@ -24,10 +24,10 @@ android {
             useSupportLibrary = true
         }
 
-        buildConfigField("String", "ISSUER", oktaProperties.getProperty("issuer"))
-        buildConfigField("String", "CLIENT_ID", oktaProperties.getProperty("clientId"))
-        buildConfigField("String", "SIGN_IN_REDIRECT_URI", oktaProperties.getProperty("signInRedirectUri"))
-        buildConfigField("String", "SIGN_OUT_REDIRECT_URI", oktaProperties.getProperty("signOutRedirectUri"))
+        buildConfigField("String", "ISSUER", "\"${oktaProperties.getProperty("issuer")}\"")
+        buildConfigField("String", "CLIENT_ID", "\"${oktaProperties.getProperty("clientId")}\"")
+        buildConfigField("String", "SIGN_IN_REDIRECT_URI", "\"${oktaProperties.getProperty("signInRedirectUri")}\"")
+        buildConfigField("String", "SIGN_OUT_REDIRECT_URI", "\"${oktaProperties.getProperty("signOutRedirectUri")}\"")
 
         manifestPlaceholders["webAuthenticationRedirectScheme"] = oktaProperties.getProperty("signInRedirectUri")
     }
diff --git a/okta.properties b/okta.properties
index affb3de..533dd7d 100644
--- a/okta.properties
+++ b/okta.properties
@@ -1,5 +1,4 @@
-issuer="https://<yourOrgDomain>/oauth2/default"
-clientId="<yourClientId>"
-signInRedirectUri="<signInRedirectUri>"
-signOutRedirectUri="<signOutRedirectUri>"
-redirectUriScheme="<reverseDomain>"
\ No newline at end of file
+issuer=https://<yourOrgDomain>/oauth2/default
+clientId=<yourClientId>
+signInRedirectUri=<signInRedirectUri>
+signOutRedirectUri=<signOutRedirectUri>
\ No newline at end of file

```
There is still a remaining issue with redirect in the sample, which is happening due to using rememberCoroutineScope(). The coroutine scope provided by rememberCoroutineScope gets cancelled when the app leaves the composition (which happens during web browser redirect).

**Comment by kkiermasz** [comment]
@rajdeepnanua-okta 
Thank you very much for your help! Now it works on my side too!
If there's any way I can buy you a coffee let me know :)
