### ISSUE TITLE
Make CredentialBootstrap.reset() visible for testing, or make CredentialBootstrap a class instead of object

### ISSUE THREAD

**Issue by shekibobo** [okta/okta-mobile-kotlin#257]
### Describe the feature request?

Writing tests around Okta have been very difficult because of the fact that `CredentialBootstrap` is an `object`, rather than a `class` that can be instantiated. True singletons can be problematic when coding, especially when testing. Because it is an `object`, it doesn't get reset in between tests, but rather sticks around for as long as the program exists in memory, meaning I can't test things that use `CredentialBootstrap` in more than one single test method without them failing. 

I've imported some of the `test-helpers` classes into my own project to perform tests using the Okta system:

```kotlin
class OktaUserAuthenticatorTest {
    @get:Rule
    val okta = OktaRule()

    private val credentialBootstrap by lazy {
        CredentialBootstrap.apply {
            runCatching {
                initialize(
                    okta.createOidcClient(okta.createEndpoints())
                        .createCredentialDataSource(InMemoryTokenStorage())
                )
            }.onFailure { Timber.e("Failed to re-initialize CredentialBootstrap.") }
            runBlocking { defaultCredential().storeToken(null) }
        }
    }
}
```

Note that because of how `CredentialBootstrap` works, I cannot actually call `initialize` more than once without an exception being thrown. The `OidcClient` can only live as long as the `OktaRule`, which only lives as long as one single test method run. Subsequent test methods will get a new rule that can then not be used by `CredentialBootstrap`.

I have now seen that there is `CredentialBootstrap.reset()` that clears the data source, and if that could be made `@VisibleForTesting(otherwise=INTERNAL)`, that would be huge for testing, and should allow me to re-initialize the object with a new data source using the clients created by the `OktaRule` for each test.

### New or Affected Resource(s)

`CredentialBootstrap.reset()` should be made visible for testing.

### Additional Information?

There are a lot of cool things happening in this library, but I feel like using `objects` is problematic  for a number of reasons, especially dealing with testing. I've been able to get past pretty much all of them except this one.

**Comment by shekibobo** [comment]
I finally have managed to get past this by adding this before my initialization:         
```kotlin
CredentialBootstrap::class.members.find { it.name == "reset" }!!.call(CredentialBootstrap)
```

**Comment by rajdeepnanua-okta** [comment]
Hi @shekibobo, I agree that this makes testing unnecessarily difficult. I will make reset() a publicly visible method and annotate it with InternalAuthFoundationApi. After that you should be able to call reset after adding a compiler opt-in in your build (under android testOptions section) similar to this: https://github.com/okta/okta-idx-android/blob/babe429f73a5324adf58dca677d940e13e8a65e2/okta-idx-kotlin/build.gradle#L29
Does that sounds reasonable?

I'm working on a fixing a few other issues, and will let you know once a release is ready with these changes.

**Comment by shekibobo** [comment]
That looks great, thank you. It would also be really cool to see `OktaRule` make it into a testing library, but for now I've just brought some of the test helpers into my own testing library and modified where useful.
