### ISSUE TITLE
Web sign-in fails to redirect on emulators

### ISSUE THREAD

**Issue by jiaqi-transcarent** [okta/okta-mobile-kotlin#267]
### Describe the bug?

We are using this package and has been following along this [doc](https://developer.okta.com/docs/guides/sign-into-mobile-app-redirect/android/main/) for Okta redirect authentication. Everything works great on real devices but the redirect always fails on Android emulators and shows `err_unknown_url_scheme` page.

### What is expected to happen?

Redirect back to app.

https://github.com/okta/okta-mobile-kotlin/assets/102095059/5da2ccf9-21e1-44e0-a8f8-7c5696236b2e

### What is the actual behavior?

https://github.com/okta/okta-mobile-kotlin/assets/102095059/e739688c-0504-428e-9bc6-d5bc5fbd5709

### Reproduction Steps?

uncertain

### SDK Version and Artifact(s) used.

compileSdkVersion is set to 33, and how we are defining dependencies:
```
    implementation('com.okta.kotlin:auth-foundation')
    implementation('com.okta.kotlin:auth-foundation-bootstrap')
    implementation('com.okta.kotlin:oauth2')
    implementation('com.okta.kotlin:web-authentication-ui')
    implementation(platform('com.okta.kotlin:bom:1.1.5'))
```

```
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
```

### Build Information

kotlin_version = '1.7.21'

**Comment by rajdeepnanua-okta** [comment]
Hi @jiaqi-transcarent, thanks for bringing up this issue. Could you describe which emulator image you are using? I have tested redirect flows on Pixel 3 API 33 virtual device, and am not experiencing this issue.

**Comment by jiaqi-transcarent** [comment]
After more digging, I found out that this was because we were using the same scheme for `appAuthRedirectScheme` and `webAuthenticationRedirectScheme`, still not sure why this is only consistently reproducible on emulators though.
