### ISSUE TITLE
Missing capabilities to pass in `state` to OAuth2.0 Authentication Request

### ISSUE THREAD

**Issue by haroldteramotosonos** [okta/okta-mobile-kotlin#276]
### Describe the bug?

We need to pass in the `state` value to the AuthorizationCodeFlow to create context from login and authentication result redirect.  However, the `state` value cannot be customized and is always set to a random UUID.

https://github.com/okta/okta-mobile-kotlin/blob/4a2b6e01536feaae5afa11f107e2b9fb24e42cd6/oauth2/src/main/java/com/okta/oauth2/AuthorizationCodeFlow.kt#L114

On Swift okta-mobile-swift, `state` value can be customized and available as part of the constructor.
https://github.com/okta/okta-mobile-swift/blob/5a858e0d700d4c9da5f0a331bf067175d20c566c/Sources/OktaOAuth2/Authentication/AuthorizationCodeFlow.swift#L92

### What is expected to happen?

We would like to have the same capability as okta-mobile-swift and set our own `state` value.

### What is the actual behavior?

`state` value is not customizable and always set to a random UUID.

### Reproduction Steps?

Code sample:
https://github.com/okta/okta-mobile-kotlin/blob/4a2b6e01536feaae5afa11f107e2b9fb24e42cd6/oauth2/src/main/java/com/okta/oauth2/AuthorizationCodeFlow.kt#L114

### SDK Version and Artifact(s) used.

bom "1.1.2"

**Comment by rajdeepnanua-okta** [comment]
Hi @haroldteramotosonos, this seems like a reasonable ask and I will add this to the SDK shortly

**Comment by rajdeepnanua-okta** [comment]
I've merged the changes to allow this. They should be present in 1.2.1
