### ISSUE TITLE
Is a 2.0 release happening soon?

### ISSUE THREAD

**Issue by longden** [okta/okta-mobile-kotlin#301]
### Describe the feature request?

Hi, now https://github.com/okta/okta-mobile-kotlin/pull/300 has been merged in master, I was wondering if it's worth holding off for a 2.0 release before releasing an update to my app to help fix some of the issues around the token init and some of the other QOL improvement that have been made - do you have an estimated release date? 

Thanks!

### New or Affected Resource(s)

2.0 release

**Comment by rajdeepnanua-okta** [comment]
@longden, it's released now! Maven might take an hour or two to update, but all the release ceremonies are complete on my end
