### ISSUE TITLE
SAML 2.0 Support

### ISSUE THREAD

**Issue by ketan-avoma** [okta/okta-mobile-kotlin#310]
### Describe the feature request?

In your documentation, I can't see anything about "**How to integrate SAML SSO?**". Would you please let me know, does your SDK support SAML SSO integration as you provide OIDC support?

### New or Affected Resource(s)

**SSO**

**Comment by ketan-avoma** [comment]
Guys, I have figured out myself. You can close this issue. Thanks🙏

**Comment by rajdeepnanua-okta** [comment]
Hi @ketan-avoma, apologies for missing this issue earlier. This SDK is only for OAuth/OIDC, not SAML.

**Comment by ketan-avoma** [comment]
Thanks @rajdeepnanua-okta for the information. 🙏
